### ISSUE TITLE
How to use the algorithm to find circuits which have length limitation?

### ISSUE THREAD

**Issue by michealowen** [gabis7/cfinding#1]
I can understand this algorithm ,but I have no idea how to find all the elementry circuits which have a length limitation.

**Comment by gabis7** [comment]
please refer to the original code in Java : http://normalisiert.de/.  Personnaly I forgot why I used this algorithm. Sorry for that.

**Comment by michealowen** [comment]
I made some changes to the algorithm so that it can select a ring within a length limitation. Thank you anyway.
